steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '-f'
      - 'Dockerfile'
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE_NAME/$_SERVICE_NAME:$COMMIT_SHA'

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - '--image'
      - '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region'
      - $_DEPLOY_REGION
      - '--platform'
      - $_PLATFORM
      - '--cpu'
      - '1'
      - '--memory'
      - '1Gi'
      - '--concurrency'
      - '20'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '20'
      - '--min-instances'
      - '1'
      - '--cpu-boost'
      - '--cpu-throttling'
      - '--execution-environment'
      - 'gen2'
      - '--set-env-vars'
      - 'ASPNETCORE_ENVIRONMENT=Production,OcrWorker__Enabled=false,OcrWorker__ExecutionMode=Web'
      - '--set-secrets'
      - 'ConnectionStrings__DefaultConnection=DefaultConnection:latest'
      - '--set-cloudsql-instances'
      - 'vfos-demo:us-central1:dms-instance-v3'
      - '--quiet'

timeout: 1200s

images:
  - '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE_NAME/$_SERVICE_NAME:$COMMIT_SHA'

substitutions:
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _DEPLOY_REGION: us-central1
  _SERVICE_NAME: dms
  _PLATFORM: managed


options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
